version: "2.4"

services:
  darwinia-link:
    image: darwinia/link
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASS: 'helloload'
      MYSQL_DB: 'darwinia-dapp'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ETHSCAN_KEY: 'G78R6SGMHGXSMXZCBDW8WE716YQFQGJ68F'
      INFURA: '1bb85682d6494e219803bab49a4813dc'
      GIN_MODE: 'release'
    ports:
      - '5333:5333'
    networks:
      - app_net

networks:
  app_net:
    external: true
