version: "2.4"

services:
  darwinia-link: &app_base
    image: darwinia/link
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASS: 'helloload'
      MYSQL_DB: 'darwinia-dapp'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ETHSCAN_KEY: ''
      INFURA: ''
      GIN_MODE: 'release'
    ports:
      - '5333:5333'
    networks:
      - app_net
  darwinia-link-daemon:
    <<: *app_base
    image: darwinia/link
    ports: []
    command: ["/app/link","observer"]
networks:
  app_net:
    external: true
