name: Staging
on:
  push:
    branches: [master, feature/github-actions]
    # tags: ['*']

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCR_SA_KEY }}
          registry: asia.gcr.io
          repository: ${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}
          add_git_labels: true
          tag_with_sha: true
          tag_with_ref: false # Do not tag on every individual branch

      - uses: ./.github/actions/trigger-deployment
        with:
          deploy_phase: staging
          trigger_token: ${{ secrets.ITERING_DEPLOYMENT_TRIGGER_TOKEN }}
          trigger_endpoint: ${{ secrets.ITERING_DEPLOYMENT_TRIGGER_ENDPOINT }}
