name: Staging
on:
  push:
    branches: ['master']
    # tags: ['*']

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCR_SA_KEY }}
          registry: asia.gcr.io
          repository: ${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}
          add_git_labels: true
          # cache_froms: asia.gcr.io/${{ secrets.GCR_PROJECT_ID }}/${{ github.repository }}:latest
          # tags: latest
          tag_with_sha: true
          tag_with_ref: false # Do not tag on every individual branch

      - name: Trigger deployment
        env:
          DEPLOY_PHASE: staging
        run: |
          export IMAGE_TAG=$(echo "sha-$GITHUB_SHA" | cut -c -11)
          export DESCRIPTION="GitHub Actions Context:
          * Run ID: ${{ github.run_id }}
          * Commit: ${{ github.sha }}
          * Ref: ${{ github.ref }}
          "
          curl -fsSL -o /dev/null -X POST \
            -F "token=${{ secrets.ITERING_DEPLOYMENT_TRIGGER_TOKEN }}" \
            -F "ref=master" \
            -F "variables[DEPLOY_PHASE]=$DEPLOY_PHASE" \
            -F "variables[DEPLOY_PROJECT]=${{ github.repository }}" \
            -F "variables[DEPLOY_IMAGE_TAG]=$IMAGE_TAG" \
            -F "variables[DEPLOY_DESCRIPTION]=$DESCRIPTION" \
            "${{ secrets.ITERING_DEPLOYMENT_TRIGGER_ENDPOINT }}"
